#!/bin/sh

# color
alias ls='exa -al'
alias grep='grep --color=auto'

# platformio
alias piorun='pio run --target upload'
alias piomonitor='pio device monitor'

# dotfiles
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

# suckless
alias strc='nvim ~/.config/st/config.def.h'
alias dwmrc='nvim ~/.config/dwm/config.def.h'
alias xinitrc='nvim ~/.xinitrc'

# neovim
alias nvimrc='nvim ~/.config/nvim/init.vim'

# zsh
alias zshrc='nvim ~/.config/zsh/.zshrc'
alias aliasrc='nvim ~/.config/aliasrc'
alias zshenv='nvim ~/.config/env'

# cleanup
alias mocp="mocp -M "$XDG_CONFIG_HOME"/moc"
alias irssi="irssi --config="$XDG_CONFIG_HOME"/irssi/config --home="$XDG_DATA_HOME"/irssi"

alias checkip="python ~/Projects/python/automation/check_ip.py"
alias venv="source venv/bin/activate"
