#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10
bspc config normal_border_color "#1e1e1e"
bspc config focused_border_color "#377375"
bspc config automatic_scheme longest_side

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating center=true
bspc rule -a LibreWolf
bspc rule -a mpv
bspc rule -a TelegramDesktop state=floating center=true
bspc rule -a Transmission-gtk state=floating center=true
bspc rule -a Tor\ Browser state=floating center=true

$HOME/.config/polybar/launch.sh --blocks
wallpaper &
blur &
lg &
